[build]
builder = "dockerfile"
dockerfile = "Dockerfile"

[deploy]
startCommand = "npm start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
PORT = "3001"
NODE_ENV = "production"
OCPP_GATEWAY_JWT = "supersecret" 