[build]
builder = "nixpacks"

[build.nixpacksConfig]
packages = ["nodejs-20_x", "npm-10_x"]

[deploy]
startCommand = "npm run start:prod"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10 